### ISSUE TITLE
pip install yolov5

### ISSUE THREAD

**Issue by fcakyon** [kadirnar/yolov5-pytorch#1]
@kadirnar eline saglik tutorial icin. Kurulum basliginda git clone alternatifi olarak yolov5 pip paket kurulumunu da anlatabilirsin: https://pypi.org/project/yolov5/

Pip paketi ile kurulursa mevcut projelere entegrasyonu daha kolay hale geliyor :)

**Comment by kadirnar** [comment]
@fcakyon Yolov5 ile çok fazla çalışma imkanım olmamıştı. Deneme amaçlı bir tutarial oluşturmak istedim. Yakın zamanda daha okunaklı hale getireceğim. Tavsiye için teşekkür ederim.
