### ISSUE TITLE
Büyük nesneler için deneme yaptınız mı?

### ISSUE THREAD

**Issue by abdullahbas** [kadirnar/yolov5-pytorch#3]
Elinize sağlık çok güzel görünüyor. 128*128 boyutundan büyük olan nesneleri tanımada herhangi test metriği denediniz mi? Mesela sistemi hibrid planlayarak ilk önce büyük nesneleri aldıktan sonra o bölgeyi karartarak zoomshot yapsanız iki tarafı da cover edersiniz sanırım. Bu senaryoda SAHİ küçük nesneler için çalışacak gibi duruyor ki bu durumda genelde detektörlerin zayıf kaldığı kısım o açıdan önemli bir çalışma olmuş. Gerçi bununla alakalı sanırım SAHİ reposuna contribute etmem gerekiyor.

**Comment by kadirnar** [comment]
Teşekkür ederim. Büyük nesneler de normal yolov5 iyi iş çıkardığı için tanımakta zorlandığı kısımlara yönelik bir çalışma yaptım. Aslında buradaki önemli olan şeylerden birisi de sahi algoritmasınıdaki img size boyutları diyebilirim.Ben elma resimlerinde 64x64 değerlerini de verdim fakat optimum değeri 128x128 oldu. Yani bu yüzden veri setine göre optimum boyutlarını seçmek daha doğru sonuçlar veriyor.

Bundan sonraki çalışamalar da uydu görüntüleri üzerine olacak. Eğer tavsiye edeceğin farklı veri seti olursa onlarla ilgili çalışma da yapabilirim.

**Comment by fcakyon** [comment]
Merhaba @abdullahbas, SAHI'nin gelistiricilerindenim. SAHI dilimlenmis tahmin yaparken ek olarak tam boyutta bir standart tahmin de aliyor. Bu sekilde dilim boyutundan daha buyuk olan objeleri de yakalamis oluyor. En son dilimlenmis ve full tahminlere postprocess uygulayarak birlestiriyor tum tahminleri. Dilerseniz full boyutta tahmin yapma ozelligini bu parametre ile kapatabilirsiniz: https://github.com/obss/sahi/blob/f9bbcdb0298e509d7431ed8af0283c2072a6090a/sahi/predict.py#L108

Yorumlariniz icin cok tesekkurler, baska soru ve tavsiyeleriniz varsa severek yanitlayabilirim 👍

**Comment by fcakyon** [comment]
> Teşekkür ederim. Büyük nesneler de normal yolov5 iyi iş çıkardığı için tanımakta zorlandığı kısımlara yönelik bir çalışma yaptım. Aslında buradaki önemli olan şeylerden birisi de sahi algoritmasınıdaki img size boyutları diyebilirim.Ben elma resimlerinde 64x64 değerlerini de verdim fakat optimum değeri 128x128 oldu. Yani bu yüzden veri setine göre optimum boyutlarını seçmek daha doğru sonuçlar veriyor.
> 
> Bundan sonraki çalışamalar da uydu görüntüleri üzerine olacak. Eğer tavsiye edeceğin farklı veri seti olursa onlarla ilgili çalışma da yapabilirim.

Evet dogru bir tespit, obje buyuklugune gore optimum dilim (slice) boyutu ve overlap miktari da degisiyor 👍

**Comment by abdullahbas** [comment]
@fcakyon  teşekkürler yanıtlar için. SAHI içerisine zoomshot eklenip aspect ratio korunarak scale up yapılıp tahminleme yapılabilir. Mesela sizin reponuzdaki GIF üzerinde direkt bir girdi durumu var uzaktaki arabalar detektör için çok küçük kalabilir. Real time performansı ile alakalı sorular ortaya çıkabilir bu durumda da. Ayrıca sormak istediğim diğer bir konu da ilk tam boyutta algılama yapıldıktan sonra o kısım tekrar alınıyor mu değerlendirmeye?

**Comment by fcakyon** [comment]
> @fcakyon teşekkürler yanıtlar için. SAHI içerisine zoomshot eklenip aspect ratio korunarak scale up yapılıp tahminleme yapılabilir. Mesela sizin reponuzdaki GIF üzerinde direkt bir girdi durumu var uzaktaki arabalar detektör için çok küçük kalabilir. Real time performansı ile alakalı sorular ortaya çıkabilir bu durumda da. Ayrıca sormak istediğim diğer bir konu da ilk tam boyutta algılama yapıldıktan sonra o kısım tekrar alınıyor mu değerlendirmeye?

Dediginiz gibi bir zoomshot yapiliyor, yani kesilen bolgeler belli bir oranla aspect ratio korunarak interpolate edilerek modelere giriliyor. GIF bu anlamda tam olarak yansitmiyor calisma prensibini. Ve evet orada bir performans/hiz trade off'u var, hiz isteyenler zoom oranini azaltip kullanabilir ya da kullandigi model yeterince hizliysa performans arttirmak icin zoom oranini daha da arttirabilir.

[slice_height, slice_width](https://github.com/obss/sahi/blob/f9bbcdb0298e509d7431ed8af0283c2072a6090a/sahi/predict.py#L104) buyuklugunde kesilen dilimler uzun kenari [image_size](https://github.com/obss/sahi/blob/f9bbcdb0298e509d7431ed8af0283c2072a6090a/sahi/predict.py#L103) parametresi kadar olacak sekilde buyutulerek modele girdi olarak veriliyor.

**Comment by fcakyon** [comment]
> Ayrıca sormak istediğim diğer bir konu da ilk tam boyutta algılama yapıldıktan sonra o kısım tekrar alınıyor mu değerlendirmeye?

Buyuk objenin tespit edildigi bolgede kucuk objeler de olabilir diye o bolgeye karartma uygulamadan tekrar obje tespiti uygulaniyor. Dedigini gibi bir yaklasimin da faydasi olabilir bazi durumlarda 👍
